const instruments = [
  {
    id: 'one',
    title: 'High Tom',
    img: require('./imgs/HighTom.png'),
    audio: require('./sounds/highTom.mp3'),
    keycode: 81,
    keyboard: 'Q',
  },
  {
    id: 'two',
    title: 'Floor Tom',
    img: require('./imgs/floorTom.png'),
    audio: require('./sounds/floorTom.mp3'),
    keycode: 87,
    keyboard: 'W',
  },
  {
    id: 'three',
    title: 'Mid Tom',
    img: require('./imgs/MidTom.png'),
    audio: require('./sounds/lowTom.mp3'),
    keycode: 69,
    keyboard: 'E',
  },
  {
    id: 'four',
    title: 'Clap',
    img: require('./imgs/Clap.png'),
    audio: require('./sounds/clap.mp3'),
    keycode: 65,
    keyboard: 'A',
  },
  {
    id: 'five',
    title: 'Snare',
    img: require('./imgs/Snare.png'),
    audio: require('./sounds/snare.mp3'),
    keycode: 83,
    keyboard: 'S',
  },
  {
    id: 'six',
    title: 'Open Hit Hat',
    img: require('./imgs/OpenHit-Hat.png'),
    audio: require('./sounds/open hit-hat.mp3'),
    keycode: 68,
    keyboard: 'D',
  },
  {
    id: 'seven',
    title: 'Hit Hat',
    img: require('./imgs/Hit-Hat.png'),
    audio: require('./sounds/hit-hat.mp3'),
    keycode: 90,
    keyboard: 'Z',
  },
  {
    id: 'eight',
    title: 'Kick',
    img: require('./imgs/Kick.png'),
    audio: require('./sounds/kick.mp3'),
    keycode: 88,
    keyboard: 'X',
  },
  {
    id: 'nine',
    title: 'Crash Cymbal',
    audio: require('./sounds/crashCymbal.mp3'),
    img: require('./imgs/crashCymbal.png'),
    keycode: 67,
    keyboard: 'C',
  },
];
export default instruments;
